- name: Download wordpress
  ansible.builtin.get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: "{{ dest }}"

- name: Extract wordpress
  ansible.builtin.unarchive:
    src: "{{ dest }}"
    dest: /tmp
    remote_src: yes

- name: Copy wordpress with owner and permissions
  ansible.builtin.copy:
    src: /tmp/wordpress/.
    dest: /var/www/html
    owner: www-data
    group: www-data
    mode: '0755'
    remote_src: yes

- name: Delete index.html
  ansible.builtin.file:
    path: /var/www/html/index.html
    state: absent

- name: Copy wp-config 
  ansible.builtin.template:
    src: /home/ubuntu/ansible-august-2024/Roles/wordpress/files/wp-config-sample.php.j2
    dest: /var/www/html/wp-config.php


