- name: Install dependencies
  ansible.builtin.apt:
    name: 
      - php 
      - libapache2-mod-php
      - php-mysql 
      - php-xml 
      - php-mbstring
      - php-curl 
      - php-zip
    state: present

  
  #sudo apt install php libapache2-mod-php php-mysql php-xml php-mbstring php-curl php-zip
